site_name: DSSG Hitchhickers guide
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'deep orange'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'bubble_chart'
  favicon: 'assets/images/favicon.ico'

docs_dir: sources
repo_name: 'dssg/hitchhikers-guide'
repo_url: https://github.com/dssg/hitchhikers-guide
edit_uri: ''
site_description: 'DSSG Hitchhikers guide'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/dssg/hitchhikers-guide'
    - type: 'twitter'
      link: 'https://twitter.com/datascifellows'
    - type: 'linkedin'
      link: 'https://linkedin.com/company/center-for-data-science-and-public-policy-university-of-chicago'

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"
      baselevel: 1
      toc_depth: 3
      separator: "-"
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.extrarawhtml
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - "js/mermaid.min.js"
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - Home: README.md
  - What is in this curriculum?: what-is-dssg.md
  - DSSG Locations: host-cities.md
  - DSSG Manual (for summer fellows):
      - What is in this manual: dssg-manual/README.md
      - Goals of the Fellowship: dssg-manual/conduct-culture-and-communications/goals.md
      - The DSSG Environment: dssg-manual/conduct-culture-and-communications/environment.md
      - Summer overview: dssg-manual/summer-overview/README.md
      - Code of conduct: dssg-manual/conduct-culture-and-communications/README.md
  - Curriculum:
      - What is in this curriculum: curriculum/README.md
      - Sample curriculum for Summer 2019: curriculum/sample.md
      - Skills you need throughout a project:
            - Ethics, Bias, Fairness: curriculum/skills/ethics_bias_fairness.md
            - Communication:
                  - Intro: curriculum/communication/README.md
                  - Presentations and communications: curriculum/communication/presentation-on-presentations.pdf
                  - Writing reports: curriculum/communication/writing.md
                  - Visualization: curriculum/eda/visualization.md
                  - User interface: curriculum/communication/user_interface.md
            - Software Practices:
                  - Intro: curriculum/skills/software_good_practices.md
                  - Programming best practices: curriculum/4_programming_best_practices/README.md
            - Domain Understanding: curriculum/skills/domain_understanding.md
      - Project Scoping:
          - Scoping overview: curriculum/scoping/overview.md
          - Project workflow: curriculum/scoping/project_workflow.md
          - Data Maturity evaluation: curriculum/scoping/dme.md
          - Intro to data analysis methods: curriculum/scoping/analysis_methods.md
          - Project deliverables: curriculum/scoping/deliverables.md
      - Before you start: curriculum/0_before_you_start/README.md
      - Tech setup:
          - Software you need: curriculum/setup/you_need.md
          - Setting up machines: curriculum/setup/machines.md
          - Command line intro: curriculum/setup/cli.md
          - Git and github basic: curriculum/setup/git.md
          - Good software practices: curriculum/software/good_practices.md
          - Python: curriculum/software/basic_python.md
          - SQL: curriculum/software/basic_sql.md
          - Software testing: curriculum/software/testing.md
          - Good repos: curriculum/setup/good_repos.md
      - Getting, storing, and linking data:
          - Intro: curriculum/1_getting_and_keeping_data/README.md
          - Data security: curriculum/get_data/security.md
          - Get data:
              - APIs and scrapping: curriculum/get_data/scrapping.md
              - Working with images: curriculum/get_data/images.md
              - Working with text: curriculum/get_data/text.md
              - Flat files: curriculum/get_data/flat_files.md
          - Store data:
              - ETL - cleaning, loading: curriculum/store_data/etl.md
              - DBs:
                  - Why a DB?: curriculum/dbs/why.md
                  - Designing a DB: curriculum/dbs/relational_design.md
                  - Getting data in: curriculum/dbs/getting_data_in.md
                  - Getting data out: curriculum/dbs/getting_data_out.md
                  - Analyzing data (SQL): curriculum/software/sql_data_analysis.md
              - Other types of DBs: curriculum/dbs/other_types.md
          - Link data:
              - Record linkage: curriculum/link_data/record_linkage.md
      - Data exploration:
            - Intro: curriculum/2_data_exploration_and_analysis/README.md
            - Introduction to EDA: curriculum/eda/intro.md
            - Visualization: curriculum/eda/visualization.md
            - SQL: curriculum/software/sql_data_analysis.md
            - pandas: curriculum/software/python_pandas.md
            - GIS: curriculum/eda/gis.md
            - Text: curriculum/eda/text.md
            - Network: curriculum/eda/network.md
            - Tableau (?): curriculum/eda/tableau.md
            - Data stories concept and code: curriculum/eda/data_stories.md
            - ML as a data exploration tool (Clustering): curriculum/eda/clustering.md
      - Computational and Data Analysis Methods:
            - Intro: curriculum/3_modeling_and_machine_learning/README.md
            - Machine Learning: curriculum/3_modeling_and_machine_learning/README.md
            - Social Sciences: curriculum/3_modeling_and_machine_learning/README.md
            - Operations Research: curriculum/3_modeling_and_machine_learning/README.md
            - Machine learning methods: curriculum/ml/methods.md
            - Causal inference methods: curriculum/methods/causal_inference.md
            - Social science methods: curriculum/methods/social_science.md
            - Other statistical analysis methods: curriculum/methods/statistical_analysis.md
            - OR/optimization methods: curriculum/methods/or.md
      - Problem Templates in Social Good and Public Policy: curriculum/ml/templates.md
      - Practical Steps in Using Machine Learning to Solve Social Problems:
            - Building an ML Pipeline:
                - ML pipeline I: curriculum/ml/pipeline.md
                - ML pipeline II: curriculum/ml/pipeline_ii.md
            - Set up problem:
                - ML problem formulation: curriculum/ml/problem_formulation.md
                - ML Checklist: curriculum/ml/checklist.md
                - Templates of policy problems: curriculum/ml/templates.md
            - Labels/Outcomes:
                - One or many: curriculum/ml/labels/one_or_many.md
                - Implications of a label: curriculum/ml/labels/implications.md
            - Features/Predictors:
                - Feature engineering: curriculum/ml/feature_engineering/intro.md
                - Workshop on feature engineering: curriculum/ml/feature_engineering/workshop.md
                - Case studies: curriculum/ml/feature_engineering/case_studies.md
            - Validation Methodology:
                - Process and goal: curriculum/ml/validation/process_and_goal.md
                - K-fold cross-validation: curriculum/ml/validation/kfold.md
                - Temporal cross-validation: curriculum/ml/validation/tcc.md
                - Field trials: curriculum/ml/validation/field_trials.md
            - Evalution Metrics:
                - Overview: curriculum/ml/metrics/overview.md
                - Examples: curriculum/ml/metrics/examples.md
            - Models/Methods:
                - Machine learning methods: curriculum/ml/methods.md
                - Practical tips on how to use them, parameters, etc.: curriculum/ml/tips.md
            - Model selection:
                - Audition: curriculum/ml/selection/audition.md
                - What metrics do we care about?:
                    - Performance: curriculum/ml/selection/performance.md
                    - Stability: curriculum/ml/selection/stability.md
                    - Interpretability: curriculum/ml/selection/interpretability.md
                    - Bias: curriculum/ml/selection/bias.md
            - Postmodeling:
                - Model understanding: curriculum/ml/postmodeling/understanding.md
                - Feature importance: curriculum/ml/postmodeling/feature_importance.md
                - Comparing different models: curriculum/ml/postmodeling/model_comparison.md
                - Comparing lists: curriculum/ml/postmodeling/list_comparison.md
                - Error analysis: curriculum/ml/postmodeling/error_analysis.md
                - Bias analysis: curriculum/ml/postmodeling/bias_analysis.md
            - Experimental design:
                - Experiment design: curriculum/experimental_design/intro.md
                - Case studies: curriculum/experimental_design/case_studies.md
      - Deployment and Maintenance:
          - How to deploy: curriculum/deployment/how_to.md
          - Monitor: curriculum/deployment/monitor.md
          - Update: curriculum/deployment/update.md
          - Advanced pipelines: curriculum/deployment/advanced_pipelines.md
